version: "3.3"

networks:
  web:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK}

services:

  centos-7:
    restart: always
    build: centos-7
    container_name: centos-7
    hostname: centos-7
    ports:
      - 6666
    volumes:
      - ${WORKPLACE_PWD}:/workspace
    mac_address: ${NETWORK_CENTOS_MAC}
    networks:
      web:
        ipv4_address: ${NETWORK_CENTOS_IP}

volumes:
  my_data:
