version: "3.3"

networks:
  web:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK}

services:

  #  centos-7:
  #    restart: always
  #    build: ./images/centos-7
  #    container_name: centos-7
  #    hostname: centos-7
  #    ports:
  #      - 6666
  #    volumes:
  #      - ${WORKPLACE_PWD}:/workspace
  #    mac_address: ${NETWORK_CENTOS_MAC}
  #    networks:
  #      web:
  #        ipv4_address: ${NETWORK_CENTOS_IP}

  ubuntu-18:
    restart: always
    build: ./images/ubuntu-18
    container_name: ubuntu-18
    hostname: ubuntu-18
    ports:
      - 6677
    volumes:
      - ${WORKPLACE_PWD}:/workspace
    mac_address: ${NETWORK_UBUNTU_MAC}
    networks:
      web:
        ipv4_address: ${NETWORK_UBUNTU_IP}

volumes:
  my_data:
